name: Auto Deploy to VPS Docker
# Menentukan kapan pipeline ini berjalan
on:
  push:
    branches:
      - main # Berjalan hanya ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Eksekusi Remote SSH ke VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
      username: ${{ secrets.SERVER_USERNAME }}
      key: ${{ secrets.SERVER_SSH_KEY }}
      port: 22

  # Skrip otomatisasi yang akan dijalankan di dalam VPS
      script: |

  # Pergi ke folder proyek (asumsi folder sudah pernah di-clone sebelumnya)
        cd /root/modul4-compose
        
        # Tarik kode terbaru
        git pull origin main
        docker build -t
        docker compose up -d --build
        docker image prune -f